<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enroll</name>
   <tag></tag>
   <elementGuidId>b4a3b9a2-aca0-4c6b-9087-eb6cb441e4f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tutor-btn-enroll.tutor-btn.tutor-course-purchase-btn.btn-enroll-view-course</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f02f07f8-bb38-47e5-8c02-1c196b2b0691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a58e0c11-79c7-4c9b-8b7c-2739bdaeeaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course</value>
      <webElementGuid>362e4cd4-7bd8-4c51-880c-c9b2f3808417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e51c57d5-5a5b-4c1e-8ff4-1ee14d43ee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>32800a5a-a3a1-496d-9861-a8a17c9086d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Enroll				</value>
      <webElementGuid>70770d55-de5c-4f40-8dfb-3344b6088854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-items-course&quot;)/div[@class=&quot;col-md-8 col-11 mb-sm-2&quot;]/div[@class=&quot;skillate-course-cart-btn d-lg-block&quot;]/div[@class=&quot;enroll-course-top enroll-course-element enroll-course-position&quot;]/div[@class=&quot;tutor-single-add-to-cart-box cart-required-login&quot;]/form[@class=&quot;tutor-enroll-form enroll-course-form&quot;]/div[@class=&quot;tutor-course-enroll-wrap&quot;]/button[@class=&quot;tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course&quot;]</value>
      <webElementGuid>19d2e560-3629-4ee4-8815-ff3ef9c494d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>c4c5c21a-74ac-48c0-b842-66e768d01d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-items-course']/div[5]/div/div/div/form/div/button</value>
      <webElementGuid>4b98c5aa-075a-4880-9eae-91bd98e189cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate this course'])[1]/following::button[1]</value>
      <webElementGuid>dc1da751-100e-4e7a-a546-984e16e62582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::button[1]</value>
      <webElementGuid>711ee593-e3e2-4730-abe1-2ccc43352294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[2]</value>
      <webElementGuid>245f9859-ca2c-4253-87af-b18583906ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enroll']/parent::*</value>
      <webElementGuid>7cb399fa-a0af-4f52-bb93-28efb402baf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>a5a97052-6e6c-44ff-b426-fba0f20d20a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
										Enroll				' or . = '
										Enroll				')]</value>
      <webElementGuid>afcb82ca-3c8b-4233-b534-0f1dff457e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
