<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up now_password</name>
   <tag></tag>
   <elementGuidId>a6b94f7e-291a-4bcc-a39f-3d9d76f3f388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cba0c70-e20b-4682-a77a-44f26150c08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1c96e6f5-3d13-4a5f-89d9-3a2838865ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>class-color-placeholder</value>
      <webElementGuid>09ac2de3-f604-4555-b683-3398ce092ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password2</value>
      <webElementGuid>768c23f6-0052-4fe8-bf3a-d615233ea6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ab963b2c-c82c-46a3-9759-ef2acaadecf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4d95cc64-d096-4e74-999e-3e87b9daf6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password2&quot;)</value>
      <webElementGuid>534b725e-bb49-45cf-b022-8e9b18950411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password2']</value>
      <webElementGuid>28d3d489-d883-4eab-b5af-65b95b8aef35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/input[2]</value>
      <webElementGuid>2d5baf9d-9c68-4a8b-97ef-8c89c0929f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/input[2]</value>
      <webElementGuid>ff8c7079-7c45-4cf6-b0c3-2842d6291ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'password2' and @placeholder = 'Password' and @name = 'password']</value>
      <webElementGuid>aeb84fba-fd04-456a-9197-eea038a81abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
