<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up now_username</name>
   <tag></tag>
   <elementGuidId>e6f54647-1695-4b91-ae26-1b3dba79566f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#username2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2064fccd-4b39-4aa5-a701-4388e31d9bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89188b90-ae44-49c3-884e-7941b4dec295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>class-color-placeholder</value>
      <webElementGuid>473729d3-8ef9-485c-b781-4438c7b74994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username2</value>
      <webElementGuid>9e71d475-a7b4-433b-b864-1ba83a39eaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>357857d4-6772-4a78-b431-e16d3ce3ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>0e6221d9-1213-4d4d-bad7-fa41d0ad5a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username2&quot;)</value>
      <webElementGuid>71f97c8e-0da6-4ebf-a742-92287ef9b953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username2']</value>
      <webElementGuid>20805116-7987-49b9-9c7d-0f01e31600a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/input</value>
      <webElementGuid>e66a8b6b-6789-4e16-8394-0c9752dd27fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/form/input</value>
      <webElementGuid>0050782e-84c5-417d-9249-75df26bb6b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'username2' and @name = 'username' and @placeholder = 'Email']</value>
      <webElementGuid>6fda94b7-da9b-40be-859d-7219542f3efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
