<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_phone</name>
   <tag></tag>
   <elementGuidId>d791b7b1-6338-4e46-bcbc-734db1f4c863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6677522f-9f3e-4a3e-91bd-6199f32b71d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f294e2df-ecd7-4e29-b5b5-75419fc4a368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>7ead8b95-8939-495b-8806-959b6d98b3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>9a737a72-e865-47ef-afb8-2c4ed6641d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>afd976dd-bbd6-4dca-b7b7-20211b3d428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0289928289</value>
      <webElementGuid>c5dc5d94-e0ab-4967-8980-5fdcfc35c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>38d973ad-6d53-46e7-b826-c66631f72a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone&quot;)</value>
      <webElementGuid>133f5bbd-089b-4b16-995d-e7035b166a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_phone']</value>
      <webElementGuid>d4ee407c-33e3-4250-9e3e-9cf9ab179bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']/span/input</value>
      <webElementGuid>047d7599-4ab9-4988-91b3-ab6127e12d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/input</value>
      <webElementGuid>e48e7bfa-d6c0-41dd-a3b2-a05eba5f9c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'billing_phone' and @id = 'billing_phone']</value>
      <webElementGuid>0be68bfb-852a-4372-a826-7626b58b6fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
