<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_company</name>
   <tag></tag>
   <elementGuidId>50aea5c2-8ae8-4378-929a-b0712a0eb916</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c7c8bc0-ff50-4964-b300-e2b61c7c02c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39023d91-2c5f-4071-b940-c2e97e9a7e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>4eca7b91-f7a6-4ddc-a049-766c756fd359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>a46e4688-503c-440c-987c-0e4b30407d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>8cf7e041-77df-4c42-8f34-bd9a2574acf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DXCABC</value>
      <webElementGuid>2a1f47d6-fa03-4110-af74-e71009f233b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>28e1f9af-dc00-446d-ba56-285dd65fa399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company&quot;)</value>
      <webElementGuid>de7c7a98-7a73-411f-8995-f6a9238486f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_company']</value>
      <webElementGuid>3e24ccb2-d89e-42b5-ad92-e394fe8659d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/span/input</value>
      <webElementGuid>c894fa07-15af-4955-8529-c2931d474b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/input</value>
      <webElementGuid>4764f3f7-5e89-4fd1-867a-223cc591d7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_company' and @id = 'billing_company']</value>
      <webElementGuid>227fe1b8-61fb-41c5-92e4-fe7ab1799146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
