<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Thank you. Your order has been received</name>
   <tag></tag>
   <elementGuidId>1a64fb1d-f799-4289-a2e8-b8df5b048cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.woocommerce-notice.woocommerce-notice--success.woocommerce-thankyou-order-received</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-9']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f16a6e71-2d61-43dc-ad37-89ef589cd6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-notice woocommerce-notice--success woocommerce-thankyou-order-received</value>
      <webElementGuid>7e4033a5-0b44-47b4-b2dd-dc103b32ddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you. Your order has been received.</value>
      <webElementGuid>b87001f3-dca8-4738-8d43-dce57f42fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-9&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-order&quot;]/p[@class=&quot;woocommerce-notice woocommerce-notice--success woocommerce-thankyou-order-received&quot;]</value>
      <webElementGuid>5abf29c9-5914-4a86-9750-fdbdfb310304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-9']/div/div/div/p</value>
      <webElementGuid>b6a7debf-3e79-4d44-a9de-c1eb81aac22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[3]/following::p[1]</value>
      <webElementGuid>d0a07c9c-ec82-44fe-b9b6-4461a0f5fd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[2]/following::p[1]</value>
      <webElementGuid>434001b1-63fc-4f19-b600-bec0df00547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you. Your order has been received.']/parent::*</value>
      <webElementGuid>28a39576-1515-4cb0-bcc6-040e7179325b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>3c947420-bf66-4c10-b80a-a561d3f43ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Thank you. Your order has been received.' or . = 'Thank you. Your order has been received.')]</value>
      <webElementGuid>fe2d5ea2-71c1-45a9-97a1-22d44fb464ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
