<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enroll</name>
   <tag></tag>
   <elementGuidId>a4969312-13b5-4015-990d-271789aa1689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tutor-btn-enroll.tutor-btn.tutor-course-purchase-btn.btn-enroll-view-course</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6161717-1048-4fe0-882d-2009729067d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d90714b8-53c6-44ed-9c8a-b51ab7b808ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course</value>
      <webElementGuid>4a7290ec-56d6-4c21-a530-727c3aca9e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>e253b94a-d8e6-46db-b7d1-b5b1335e4750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>0ad3c83e-a906-48dc-ad13-7ff7797dc160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Enroll				</value>
      <webElementGuid>496fbe94-43bf-4fe7-9227-d50a7cc904aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-items-course&quot;)/div[@class=&quot;col-md-8 col-11 mb-sm-2&quot;]/div[@class=&quot;skillate-course-cart-btn d-lg-block&quot;]/div[@class=&quot;enroll-course-top enroll-course-element enroll-course-position&quot;]/div[@class=&quot;tutor-single-add-to-cart-box cart-required-login&quot;]/form[@class=&quot;tutor-enroll-form enroll-course-form&quot;]/div[@class=&quot;tutor-course-enroll-wrap&quot;]/button[@class=&quot;tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course&quot;]</value>
      <webElementGuid>2ee60da7-617a-48a4-9c35-fac7085c6d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>9aa3010c-7744-4653-bbdc-92db445a31a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-items-course']/div[5]/div/div/div/form/div/button</value>
      <webElementGuid>2690bdf8-09ec-4cfa-827c-49b50c0ca69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate this course'])[1]/following::button[1]</value>
      <webElementGuid>f212820e-c50f-4d6f-b728-7df5a28c9050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::button[1]</value>
      <webElementGuid>9b6531f6-40e6-41d6-98c7-643ca92a4a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[2]</value>
      <webElementGuid>0b672480-8893-4eef-8e21-76c4e250862e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enroll']/parent::*</value>
      <webElementGuid>f30a3fcf-5d26-4849-8e7d-c7414fc3a5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>b67d129e-408c-417c-b2a4-098c91f0a2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
										Enroll				' or . = '
										Enroll				')]</value>
      <webElementGuid>3810dcfa-8416-48cd-88c4-b6fe4a5347a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
