<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In</name>
   <tag></tag>
   <elementGuidId>e40ce6c6-3235-4a2f-bf23-4d1982407da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.skillate-login-tab-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-registration']/div/div/div/div/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5fca3544-856c-45be-8af8-72f32b26c7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>d55c42cd-62fe-48f4-bbfd-4928989b52f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>02aeb200-fa91-40e4-8b5a-0099b36ce1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skillate-login-tab-toggle</value>
      <webElementGuid>c0b4a3ba-296a-4e74-b298-3d994b59a1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#modal-login</value>
      <webElementGuid>8ac529e9-e8f3-44b5-9aa2-1869f4e49b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log In </value>
      <webElementGuid>f62afd9e-efed-4e2d-91fc-e24fec314440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-registration&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;skillate-signin-popup-inner modal-content&quot;]/div[@class=&quot;skillate-register-body modal-body&quot;]/div[@class=&quot;skillate-signin-modal-form&quot;]/p[@class=&quot;title-small&quot;]/a[@class=&quot;skillate-login-tab-toggle&quot;]</value>
      <webElementGuid>a44a54e4-fafb-437b-84ac-57ccd46d0664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-registration']/div/div/div/div/p[2]/a</value>
      <webElementGuid>79eeafe1-3154-4b36-b83e-e3d9c894b67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In')]</value>
      <webElementGuid>23b2e77d-b238-4bca-9b65-5af5258864e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::a[1]</value>
      <webElementGuid>b8ea6f8e-f3a2-49ac-8b05-2e9934f10e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Certification Program.'])[1]/following::a[2]</value>
      <webElementGuid>07363515-0b29-4c6c-b2af-1fb3e7607b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Certification Program.'])[2]/preceding::a[1]</value>
      <webElementGuid>fd3b2c0a-093d-43ab-a4e6-c29350ba9f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In']/parent::*</value>
      <webElementGuid>8ea36fd3-29c9-49a0-8792-639225aa78a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#modal-login')])[4]</value>
      <webElementGuid>3d52d078-5ad0-4884-87ac-4dd48887bfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/p[2]/a</value>
      <webElementGuid>e5165afe-4160-4b19-bc47-ba18202d6a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#modal-login' and (text() = ' Log In ' or . = ' Log In ')]</value>
      <webElementGuid>077c4026-74bd-4c07-9ad3-4ac329194bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
