<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enroll</name>
   <tag></tag>
   <elementGuidId>ac568c0f-a2eb-4468-9acf-4841fab0e809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tutor-btn-enroll.tutor-btn.tutor-course-purchase-btn.btn-enroll-view-course</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2176a61e-2129-4d92-82cc-72bd2aadf675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c01bfd5a-fd3b-43fc-9216-041f69bd0784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course</value>
      <webElementGuid>d621088f-088e-4c0a-808b-467eea15a5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4bfe40c4-6008-4fac-aebe-d96e6e0af5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>83bfab2b-84b2-4d49-abd7-5c689e661aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Enroll				</value>
      <webElementGuid>f9dceb0c-50ca-43dc-b1d8-f15b6f037999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-items-course&quot;)/div[@class=&quot;col-md-8 col-11 mb-sm-2&quot;]/div[@class=&quot;skillate-course-cart-btn d-lg-block&quot;]/div[@class=&quot;enroll-course-top enroll-course-element enroll-course-position&quot;]/div[@class=&quot;tutor-single-add-to-cart-box cart-required-login&quot;]/form[@class=&quot;tutor-enroll-form enroll-course-form&quot;]/div[@class=&quot;tutor-course-enroll-wrap&quot;]/button[@class=&quot;tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course&quot;]</value>
      <webElementGuid>eada4411-67cb-4c92-81aa-4c69ba58b84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>8d69ceaf-b9dc-47ef-b188-bbdb82a55362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-items-course']/div[5]/div/div/div/form/div/button</value>
      <webElementGuid>810cefa3-6ed9-43ce-bd1a-5e1a1d9052e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate this course'])[1]/following::button[1]</value>
      <webElementGuid>4c1545bf-24f9-4aac-b367-1e861afc758d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/following::button[1]</value>
      <webElementGuid>54ee74c2-2549-427a-81e8-b5d4bf9c67ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[2]</value>
      <webElementGuid>0fcfdd70-86b8-4b83-a7a2-8d0e78d49e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enroll']/parent::*</value>
      <webElementGuid>0fbd67e2-8145-4bb1-94be-a174ba44162a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>7def9c33-b295-4d70-b7dd-329dfe183972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
										Enroll				' or . = '
										Enroll				')]</value>
      <webElementGuid>d9480192-e91c-44f3-8520-dffb895c5662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
