<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Katalon Certification Program_skillat_294bf0</name>
   <tag></tag>
   <elementGuidId>f27e8dfb-e6c7-43fb-bd17-c16896b834e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.skillate_btn.login_button.btn-fill.class-btn-hover-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Log In'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c3afa72-92ae-4456-a902-f51f7ba7b84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>skillate_btn login_button btn-fill class-btn-hover-login</value>
      <webElementGuid>776505d0-55d1-4547-9af9-b4e096dd3bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>1d9b6d8e-db41-41a4-a8d6-6f0baec027e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1eeb2848-4607-474c-a6cb-bf3950052ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;class-btn-login-modal&quot;]/input[@class=&quot;skillate_btn login_button btn-fill class-btn-hover-login&quot;]</value>
      <webElementGuid>a5f8a4a8-8ba1-4191-a4b0-9af89533dcad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Log In'])[4]</value>
      <webElementGuid>57a32d8b-0b56-4c3e-a5d2-2124dbc87645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/input</value>
      <webElementGuid>3eabb4e3-5947-4872-8394-72d23f36be64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>0e716476-e18c-46e9-821e-63a9886b62c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>995246de-c89b-478b-8d05-1d5633c1e162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
